version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.template
    ports:
      - "8080:80"
    command: 'bash -c "cat /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  reverse-proxy:
    build: .
    ports:
      - "8000:8000"
    entrypoint: "./target/release/reverse_proxy_test"
    # command: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    entrypoint: "./target/release/api"
    # command: 