version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    command: 'bash -c "cat /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  reverse-proxy:
    volumes:
      - ./.env:/.env
    build: .
    ports:
      - "8000:8000"
    entrypoint: "./target/release/reverse_proxy_test"
    # command: 